services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped

